### ISSUE TITLE
Setup service worker

### ISSUE THREAD

**Issue by burhanahmeed** [burhanahmeed/chat-whatsapp#4]
- Add support for PWA
- Add service workers
- Icon: https://github.com/burhanahmeed/chat-whatsapp/blob/master/public/Whatsy.png

**Comment by sankalpkotewar** [comment]
I would like to pick this issue.

**Comment by burhanahmeed** [comment]
sure, if anyone haven't took this issue... Please make a draft PR so we know if someone is working on this issue.

Cheers!
